@startuml

entity "Task" as t {
  id: bigint
  ---
  name: text
  description: text
  project_id: bigint
}

entity "Project" as p {
  id: bigint
  ---
  name: text
  description: text
}

p |o..o{ t

@enduml
