@startuml 
left to right direction 
'!pragma graphviz_dot jdot 
!pragma layout smetana 
entity "Проект" as app_program {
    *"Идентификатор" : "Целочисленный"
---
    "Мнемоника действия" : "Строка"
    "Название" : "Строка"
    "Описание" : "Строка"
    "Статус" : "Строка"
    "Оптимистичная блокировка" : "Целочисленный"
    "Флаг удаления" : "Логический"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
}

entity "Проект" as app_project {
    *"Идентификатор" : "Целочисленный"
---
    "Идентификатор программы" : "Целочисленный"
    "Мнемоника действия" : "Строка"
    "Название" : "Строка"
    "Описание" : "Строка"
    "Статус" : "Строка"
    "Оптимистичная блокировка" : "Целочисленный"
    "Флаг удаления" : "Логический"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
}

entity "Задача" as app_task {
    *"Идентификатор" : "Целочисленный"
---
    "Идентификатор проекта" : "Целочисленный"
    "Мнемоника действия" : "Строка"
    "Название" : "Строка"
    "Описание" : "Строка"
    "Статус" : "Строка"
    "Оптимистичная блокировка" : "Целочисленный"
    "Флаг удаления" : "Логический"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
}

"app_project" }--|| "app_program"
"app_task" }--|| "app_project"

@enduml
